from PIL import Image
import io
import base64
import time
import requests
import json
import os
import pandas as pd
import argparse

class AtlasAgent:
    def __init__(self):
        """
        atlas agent 
        """
        pass
        
    def compress_image(self, image_path, quality=75, max_size=(1024, 1024)):
        """compress image"""
        with Image.open(image_path) as img:
            if img.mode == 'RGBA':
                img = img.convert('RGB')
            
            img.thumbnail(max_size, Image.Resampling.LANCZOS)
            buffer = io.BytesIO()
            img.save(buffer, format="JPEG", quality=quality)
            buffer.seek(0)
            return buffer
    
    def run_gpt_api(self, prompt, base64_image):
        """
        request GPT
        """
        # api
        url = "https://api.chatanywhere.tech/v1/chat/completions"
        
        # request headers
        headers = {
            "Content-Type": "application/json",
            "Authorization": "sk-Qi2svs6TgE7uEVfKJZ3VAkOf3kT5IRYn8Xb2obJq5MdyCRqa"  # change your api key
        }    
        # 设置请求体
        data = {
            "model": "gpt-4o",  # model name
            "messages": [
                {"role": "user", "content": [
                    {"type": "text", "text": prompt},  # user question
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_image}"
                        }
                    }
                ]},
            ],
            "max_tokens": 2000, 
            "temperature": 0.7,  
            "n": 1  
        }
        
        # send post
        response = requests.post(url, headers=headers, data=json.dumps(data))
        
        # analyze resposne
        if response.status_code == 200:
            result = response.json()
            generated_text = result['choices'][0]['message']['content']
            #print("generate_message：", generated_text)
            return generated_text
        else:
            print("error code：", response.status_code)
            print("error information：", response.text) 
            return None
    
    def generate_json_str(self, result):
        """
        analyze the datasets generated by LLMs
        """
        result = result[result.index("{"):]
        last_index = -1
        for i in range(len(result)):
            if result[i] == '}':
                last_index = i
        result = result[:last_index+1]
        result = json.loads(result)
        ###sort result json dict
        sorted_items = sorted(result.items(), key=lambda x: x[1], reverse=True)[:3]
        result_fun = ""
        for fun in sorted_items:
            result_fun += fun[0] + " "
        return result_fun
    
    def evaluate_image_data(self, image_path, output_excel=None, is_dir=False):
        """
        generate the result for image/image path(for multiple images)
        """
        prompt = '''
                    SYSTEM
                    You are a senior single-cell bioinformatician.
                    
                    INPUT
                    • One composite figure.  Upper row: projection coloured by BATCH.  Lower row: projection coloured by CELL TYPE.  
                    • The left-most tile is “Unintegrated”; the remaining tiles are candidate methods.
                    
                    VISUAL RUBRIC  (0 = poor, 5 = excellent)
                    M1  Batch mixing          – batch colours well intermixed inside clusters.
                    M2  Graph connectivity    – biologically related clusters remain weakly bridged.
                    M3  Cell-type silhouette  – cluster borders are crisp, single-coloured.
                    M4  Cell-type continuity  – each cell type forms one contiguous island.
                    
                    Score each method.  
                    Compute total = 0.25(M1+M2+M3+M4).  
                    
                    ### output
                    only return the sorted json for all methods and its score. 
                    example: {"method 1": 4.0, "method 2": 3.5 ....}
                    ###Do not return any details of score, only output the json
                    '''
        if not is_dir:
            #generate for single image
            buffer = self.compress_image(image_path, quality=100)
            base64_image = base64.b64encode(buffer.read()).decode('utf-8')
            data = self.run_gpt_api(prompt, base64_image)
            result_functions = self.generate_json_str(data)
            return result_functions
        else:
            files = [os.path.join(image_path, f) for f in os.listdir(image_path) if os.path.isfile(os.path.join(image_path, f))]
            all_dict = {}
            for image in files:
                buffer = self.compress_image(image, quality=100)
                base64_image = base64.b64encode(buffer.read()).decode('utf-8')
                data = self.run_gpt_api(prompt, base64_image)
                result_functions = self.generate_json_str(data)
                all_dict[image.replace(image_path, "")] = result_functions
            df = pd.DataFrame(list(all_dict.items()), columns=['image', 'top 3 methods'])
            df.to_excel(output_excel, index=False)
            return all_dict

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='welcome to Atlas')
    parser.add_argument('--mode', type=str, default='evaluate_image', choices=['evaluate_image', 'evaluate_multiple_images'], help='Execution mode. You can choose from evaluate_image, evaluate_multiple_images')
    parser.add_argument('--image_path', type=str, default='', help = 'please input the path of your target input image or image directories')
    parser.add_argument('--image_output_path', type=str, default='', help = 'please input the path of your target output excel for multiple images evaluation, the file name should end with xls or xlsx')

    atlasagent = AtlasAgent()
    args = parser.parse_args()
    mode = args.mode
    if mode == "evaluate_image":
        image_path = args.image_path
        data = atlasagent.evaluate_image_data(image_path=image_path)
        print("the top 3 methods are: ")
        print(data)
    elif mode == "evaluate_multiple_images":
        image_path = args.image_path
        image_output_path = args.image_output_path
        data = atlasagent.evaluate_image_data(image_path=image_path, output_excel=image_output_path, is_dir=True)
        print("the evluation has been generated in :" + image_output_path)
        
    